# The URL the site will be built for
base_url = "https://engineer-hama.github.io"

title = "HaMa"
description = ""

theme = "goyo"

[extra]
logo_text = "HaMa's Blog"
sidebar_expand_depth = 5
disable_root_sidebar_hide = true
